### ISSUE TITLE
whatweb fails

### ISSUE THREAD

**Issue by nk9** [stevemcilwain/quiver#23] opened 2020-03-16 13:04 UTC
I installed quiver and ran `qq-install`. Honestly, though, I ran out of space on the device. (A recurring theme!) But I enlarged the volume, and eventually `qq-install` completed successfully.

Then I ran `qq-scripts-recon` and left it to do its thing. When finished, I looked in `./web/<domain>.io/whatweb.txt` and found this:

```
➜  ~/bb/mai/w/lootdog.io cat whatweb.txt                                                                                                                                                  12:58:05
/home/admin/.rbenv/versions/2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- whatweb (LoadError)
	from /home/admin/.rbenv/versions/2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	from /usr/bin/whatweb:37:in `<main>'
```

Does `whatweb` need to be installed by `qq-install`?

**Comment by stevemcilwain** [comment] 2020-03-20 08:45
whatweb is installed by qq-install:

__pkgs whatweb gobuster wpscan wafw00f hydra nikto padbuster parsero dirb 

That error looks like a ruby error stemming from whatweb - not sure the cause... maybe this?
https://github.com/urbanadventurer/WhatWeb/issues/283

**Comment by stevemcilwain** [comment] 2020-03-20 08:46
Closing this since it's a tool error, not a quiver error.

**Closed as completed by stevemcilwain** 2020-03-20 08:46 UTC
Labels: wontfix

**Comment by blshkv** [comment] 2020-03-24 08:21
something is broken. Please re-open this bug

**Comment by stevemcilwain** [comment] 2020-03-24 08:28
Hi @blshkv, I am maintaining quiver, but not whatweb.  Whatweb is just installed with Kali via apt-get and I call it from my scripts.

Try opening an issue over on the WhatWeb repo:  https://github.com/urbanadventurer/WhatWeb and maybe have a look at their installation wiki:  https://github.com/urbanadventurer/WhatWeb/wiki/Installation. It looks like the error you are getting has to do with missing or broken ruby dependencies.  

Good luck!

**Comment by blshkv** [comment] 2020-03-24 08:31
yeah, sorry. Working with upstream, I found a minor error.
